services:
  backend:
    build:
      context: ./server
    container_name: backend
    # Remove this line if you don't need direct access: ports: - "8080:8080"
  environment:
    - GOTENBERG_URL=http://gotenberg:3000/forms/chromium/convert/html
  depends_on:
    - gotenberg
  restart: unless-stopped

  frontend:
    build:
      context: ./client
    container_name: frontend
    # Remove this line if you don't need direct access: ports: - "5173:5173"
    restart: unless-stopped

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg
    # Remove this line if you don't need direct access: ports: - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Service
  nginx:
    image: nginx:1.27.5
    container_name: nginx
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro # Use existing SSL certificates
      - /var/www/html:/var/www/html:ro # Webroot for validation
    depends_on:
      - backend
      - frontend
      - gotenberg
    restart: unless-stopped
