services:
  # Backend Service (Go)
  backend:
    build:
      context: ./server # Path to your backend's Dockerfile
    container_name: backend
    ports:
      - "8080:8080" # Expose backend port for direct access (optional)
    restart: unless-stopped

  # Frontend Service (Node/React)
  frontend:
    build:
      context: ./client # Path to your frontend's Dockerfile
    container_name: frontend
    ports:
      - "5173:5173" # Expose frontend port for direct access (optional)
    restart: unless-stopped

  # Nginx Service
  nginx:
    image: nginx:1.27.5
    container_name: nginx
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt        # SSL certificates
      - ./certbot/www:/var/www/certbot         # Webroot for validation
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  # Certbot Service
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # This will be overridden when we run commands manually
    command: echo "Certbot container ready"