on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
      
    - name: 🔨 Build Project
      run: |
        cd client
        npm install
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp-easyapply.alwaysdata.net
        username: easyapply_ftp
        password: ${{ secrets.SSH_PASSWORD }}
        local-dir: ./client/build
        protocol: ftps
        port: 21 # 
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          