on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: 🔨 Build Project
        run: |
          cd client
          npm install
          npm run build

      - name: 📂 Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: access-5018018253.webspace-host.com
          username: a2611640
          ssh_private_key: ${{ secrets.IONOS_SSH_KEY }}
          local_path: "./client/build/"
          remote_path: "/easyapply/client/"
          sftp_only: true
          port: 22
          rsyncArgs: "--exclude=node_modules --exclude=.git --exclude=*.log"

