on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ssh-easyapply.alwaysdata.net
        username: easyapply_ssh
        password: ${{ secrets.SSH_PASSWORD }}
        local-dir: ./client/ # The directory to upload (relative to the root of the repository)
        protocol: ftps
        port: 22 # todo replace with your web hosts ftps port